version: "3.9"
services:
  bayeue-mysql-server:
    image: mariadb:10.7
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=db_bayeue
    ports:
      - "33006:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-proot", "-e", "show schemas"]
      interval: 10s

  bayeue:
    build: .
    restart: always
    depends_on:
      bayeue-mysql-server:
        condition: service_healthy
    environment:
      DBNAME: db_bayeue
      DBUSER: root
      DBPASS: mAyZPcLvVak7OSzSrJ3B
      DBHOST: containers-us-west-190.railway.app
      DBPORT: 6907
      JWTSecret: bayeue_secret
    container_name: bayeue-1.0
    ports:
      - "19000:8080"
    env_file:
      - "./config.env"
